# Generated by Django 5.1.7 on 2025-03-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hoteles", "0001_initial"),
        ("servicios", "0002_alter_servicio_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios",
                to="hoteles.hotel",
            ),
        ),
    ]
