# Generated by Django 5.1.7 on 2025-03-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hoteles", "0001_initial"),
        ("servicios", "0003_alter_servicio_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios",
                to="hoteles.hotel",
            ),
        ),
    ]
