# Generated by Django 5.1.7 on 2025-03-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empleadohotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('recepcionista', 'Recepcionista'), ('camarista', 'Camarista'), ('mantenimiento', 'Mantenimiento'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
