# Generated by Django 5.1.7 on 2025-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado_limpieza',
            field=models.CharField(choices=[('sucia', 'Sucia'), ('en_limpieza', 'En limpieza'), ('limpia', 'Limpia')], default='sucia', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado_mantenimiento',
            field=models.CharField(choices=[('operativa', 'Operativa'), ('en_mantenimiento', 'En mantenimiento'), ('mantenimiento_realizado', 'Mantenimiento realizado')], default='operativa', max_length=30),
        ),
    ]
