# Generated by Django 5.1.7 on 2025-05-05 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_habitacion_estado_limpieza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='disponible',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='costo_por_noche',
            new_name='price_per_night',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='direccion',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='estado_limpieza',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='estado_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='propietario',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='beds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='cleaning_status',
            field=models.CharField(choices=[('dirty', 'Dirty'), ('cleaning', 'Cleaning'), ('clean', 'Clean')], default='dirty', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='maintenance_status',
            field=models.CharField(choices=[('operational', 'Operational'), ('under_maintenance', 'Under Maintenance'), ('maintenance_done', 'Maintenance Done')], default='operational', max_length=30),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='policies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='title',
            field=models.CharField(default='Standard Room', max_length=255),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite'), ('familiar', 'Familiar')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='view',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hoteles.hotel'),
        ),
        migrations.CreateModel(
            name='BathroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom', to='hoteles.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hoteles.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hoteles.habitacion')),
            ],
        ),
    ]
